// ============================================================
// DevSecOps CI Pipeline — Python Monolith (Flask Student Management App)
// Tool: Jenkins Declarative Pipeline
// Stack: Python 3.12 · Flask · pytest · Bandit · pip-audit · SonarQube · Trivy
//        · Docker Hub · GHCR · Nexus
// Credentials: sonarqube-token · github-creds · docker-creds · nexus-creds · ghcr-creds
// SonarQube server: sonar-server  |  Scanner: sonar-scanner
//
// ── REQUIRED JENKINS PLUGINS ──────────────────────────────────────────────────
//   - SonarQube Scanner Plugin    → provides withSonarQubeEnv()
//   - AnsiColor Plugin            → provides ansiColor() option
//   - Coverage Plugin             → provides recordCoverage() DSL
//                                   for Python coverage.xml (Cobertura format)
//                                   (replaces deprecated Cobertura Plugin)
//   - JUnit Plugin                → provides junit() DSL for pytest XML reports
//
// NOTE: No Pipeline Maven Integration Plugin needed — this is Python, not Java.
// NOTE: No Config File Provider Plugin needed — no settings.xml for pip.
// ──────────────────────────────────────────────────────────────────────────────
//
// ── PYTHON TOOLCHAIN DIFFERENCES FROM JAVA PIPELINE ──────────────────────────
//
//   Java Pipeline              │  This Pipeline (Python)
//   ─────────────────────────────────────────────────────────────────────────
//   mvn help:evaluate          │  python setup.py / grep __version__ / .env
//   pom.xml <version>          │  VERSION file (plain text, single source of truth)
//   mvn clean verify           │  pip install + pytest
//   JaCoCo XML (jacoco.xml)    │  pytest-cov → coverage.xml (Cobertura format)
//   SonarQube via mvn sonar:   │  SonarQube via sonar-scanner CLI
//   mvn deploy (JAR to Nexus)  │  No artifact publish — Python wheel not in scope
//   withMaven()                │  Plain sh() — pip manages its own venv
//   configFileProvider         │  Not needed — no settings.xml
//   SERVER_PORT build-arg      │  PORT build-arg (default 5000, matches Dockerfile)
//   eclipse-temurin:21-jre     │  python:3.12-slim (builder + runtime, same base)
//
// ── WHY NO NEXUS PYPI PUBLISH ────────────────────────────────────────────────
//   The Java pipeline publishes a JAR to Nexus Maven snapshots because the JAR
//   is a deployable artifact independent of the Docker image. For this Python
//   project, the deployable unit IS the Docker image — there is no wheel or
//   sdist that needs to be published separately. Docker Hub, GHCR, and Nexus
//   Docker registry receive the container image (Stages 10-12).
//
// ── TEST ISOLATION (DATABASE_URL) ────────────────────────────────────────────
//   The app uses PostgreSQL at runtime (config.py reads DATABASE_URL). The
//   tests in tests/test_app.py are purely static/unit tests using unittest.mock
//   — they import app.models directly without calling create_app(), so no
//   real database connection is needed. However, Config.validate() in
//   app/__init__.py raises EnvironmentError if DATABASE_URL is unset.
//   We set DATABASE_URL=sqlite:// (empty in-memory SQLite) for the CI test
//   stage — this satisfies the env var check without requiring PostgreSQL.
//   Tests never call create_app() so no actual DB connection is made.
//
// ── BANDIT SAST ───────────────────────────────────────────────────────────────
//   Bandit is a Python-specific static analysis tool for security issues
//   (hardcoded passwords, use of subprocess, eval, pickle, etc.).
//   It complements SonarQube (which focuses on code quality + broader SAST)
//   with Python-idiomatic security checks SonarQube misses.
//   Runs BEFORE Docker build — fail-fast on HIGH severity findings.
//
// ── PIP-AUDIT ─────────────────────────────────────────────────────────────────
//   pip-audit scans requirements.txt for known CVEs in the dependency tree
//   (queries PyPI Advisory Database + OSV). This is the Python equivalent of
//   OWASP Dependency Check used in Java pipelines. Runs alongside Trivy FS
//   scan for defense-in-depth: Trivy scans the filesystem + container image
//   layers; pip-audit specifically queries PyPI advisories for Python packages.
//
// ── SONARQUBE FOR PYTHON ──────────────────────────────────────────────────────
//   SonarQube supports Python natively. The sonar-scanner CLI is used (not the
//   Maven plugin). Coverage data is fed from coverage.xml (Cobertura format,
//   generated by pytest-cov). sonar.python.version must match the runtime
//   Python version (3.12) for accurate analysis.
// ──────────────────────────────────────────────────────────────────────────────
//
// ── MIGRATION NOTE ────────────────────────────────────────────────────────────
//   This Jenkinsfile lives at the application source repository root:
//     Repo:        ibtisam-iq/python-monolith-app
//     Script Path: Jenkinsfile
//   APP_DIR = '.' — workspace root is the application root.
// ──────────────────────────────────────────────────────────────────────────────

pipeline {

    // Restrict to Linux agents — sh/trivy/docker/bandit all require Linux.
    // Same rationale as java-monolith-app: prevents accidental Windows agent dispatch.
    agent { label 'built-in || linux' }

    // ── tools block is NOT used here.
    // Python 3.12, pip, trivy, and docker are installed system-wide on the
    // Jenkins OS and are available on OS PATH.
    // sonar-scanner is NOT installed system-wide — it is registered in
    // Manage Jenkins → Tools → SonarQube Scanner as 'sonar-scanner'.
    // SCANNER_HOME = tool 'sonar-scanner' in environment{} resolves its
    // install path at runtime; $SCANNER_HOME/bin/sonar-scanner invokes it.

    environment {
        // ── App metadata
        APP_NAME    = 'python-monolith'
        // APP_VERSION is intentionally NOT defined here.
        // It is read at runtime from the VERSION file in Stage 3 (Versioning).
        // This ensures the image tag always matches the committed version without
        // manual sync here — same pattern as java-monolith pom.xml version.

        // ── Docker Hub
        DOCKER_USER = 'mibtisam'
        IMAGE_NAME  = "${DOCKER_USER}/${APP_NAME}"
        // IMAGE_TAG set dynamically in Versioning stage

        // ── GitHub Container Registry
        GHCR_USER   = 'ibtisam-iq'
        GHCR_IMAGE  = "ghcr.io/${GHCR_USER}/${APP_NAME}"

        // ── AWS ECR  [uncomment once ECR repo is provisioned]
        // AWS_REGION     = 'us-east-1'
        // AWS_ACCOUNT_ID = '123456789012'
        // ECR_REGISTRY   = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
        // ECR_IMAGE      = "${ECR_REGISTRY}/${APP_NAME}"

        // ── Nexus Docker Registry — path-based routing
        // Image format: nexus.ibtisam-iq.com/docker-hosted/python-monolith:<tag>
        // Same Nexus instance as java-monolith; path-based routing separates repos.
        NEXUS_URL         = 'https://nexus.ibtisam-iq.com'
        NEXUS_DOCKER      = 'nexus.ibtisam-iq.com'
        NEXUS_DOCKER_REPO = 'docker-hosted'

        // ── Source directory
        // APP_DIR = '.' — this Jenkinsfile lives at the repo root.
        // All dir(APP_DIR) blocks resolve to workspace root.
        APP_DIR = '.'

        // ── Python / pip
        PYTHON          = 'python3'
        VENV_DIR        = '.venv-ci'      // isolated venv for this CI build
        PIP             = "${VENV_DIR}/bin/pip"
        PYTEST          = "${VENV_DIR}/bin/pytest"
        BANDIT          = "${VENV_DIR}/bin/bandit"
        PIP_AUDIT       = "${VENV_DIR}/bin/pip-audit"
        COVERAGE        = "${VENV_DIR}/bin/coverage"

        // ── Application server port (matches Dockerfile ARG PORT default and compose.yml)
        // Change here if application port changes — single source of truth for build-arg.
        APP_PORT = '5000'

        // ── CI database URL for test isolation
        // Config.validate() raises EnvironmentError if DATABASE_URL is unset.
        // Tests in tests/test_app.py are static unit tests using unittest.mock —
        // they never call create_app() or open a real DB connection.
        // sqlite:// (empty, in-memory) satisfies the env var presence check
        // without requiring a running PostgreSQL instance in CI.
        DATABASE_URL = 'sqlite://'

        // ── CD GitOps repo coordinates
        // Update here if the CD repo is renamed or the manifest path changes.
        CD_REPO          = 'ibtisam-iq/platform-engineering-systems'
        CD_MANIFEST_PATH = 'systems/python-monolith/image.env'

        SCANNER_HOME = tool 'sonar-scanner'
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '5'))
        timeout(time: 60, unit: 'MINUTES')
        // abortPrevious: true — explicit, version-resilient across Jenkins LTS upgrades.
        // Without it, behavior depends on Pipeline Plugin version.
        disableConcurrentBuilds(abortPrevious: true)
        timestamps()
        ansiColor('xterm')
    }

    stages {

        // ────────────────────────────────────────────────────────────────────
        // STAGE 1 — Checkout
        //
        // checkout scm uses Jenkins-injected SCM object from job config.
        // Guarantees GIT_COMMIT and GIT_BRANCH match the triggering commit —
        // critical for image tag traceability and the main-branch when{} guard.
        // Same rationale as java-monolith Stage 1.
        // ────────────────────────────────────────────────────────────────────
        stage('Checkout') {
            steps {
                echo '📥 Checking out source...'
                checkout scm
            }
        }

        // ────────────────────────────────────────────────────────────────────
        // STAGE 2 — Trivy Filesystem Scan
        //
        // Scans source tree BEFORE any build step — fail-fast principle.
        // Targets: requirements.txt (PyPI CVEs), Dockerfile (misconfig),
        //          source files (hardcoded secrets).
        //
        // Same two-pass strategy as java-monolith:
        //   Pass 1 — CRITICAL only, --exit-code 1 → fails build on finding
        //   Pass 2 — HIGH,MEDIUM only, --exit-code 0 → advisory table
        //
        // --skip-dirs .git,.venv-ci — excludes:
        //   .git: false-positive secrets in pack files + speed (same as Java)
        //   .venv-ci: if a prior build left the venv in the workspace, Trivy
        //             would scan all installed packages in it — thousands of
        //             files with no value. We scan requirements.txt directly,
        //             not the installed tree.
        //
        // LOW is excluded from FS scan intentionally — same rationale as Java:
        // source-tree LOW findings are noise. LOW IS included in image scan (Stage 9).
        //
        // archiveArtifacts: bare filename — dir(APP_DIR) sets CWD correctly.
        // allowEmptyArchive: true — prevents build failure if Trivy exits 1
        // and never writes the JSON (it writes JSON before exit code evaluation).
        // ────────────────────────────────────────────────────────────────────
        stage('Trivy Filesystem Scan') {
            steps {
                dir(APP_DIR) {
                    echo '🔎 Running Trivy filesystem scan on source tree...'
                    sh """
                        trivy fs \\
                            --cache-dir /var/cache/trivy \\
                            --skip-dirs .git,${VENV_DIR} \\
                            --scanners secret,vuln,misconfig \\
                            --exit-code 1 \\
                            --severity CRITICAL \\
                            --no-progress \\
                            --format json \\
                            --output trivy-fs-report.json \\
                            .

                        trivy fs \\
                            --cache-dir /var/cache/trivy \\
                            --skip-dirs .git,${VENV_DIR} \\
                            --scanners secret,vuln,misconfig \\
                            --exit-code 0 \\
                            --severity HIGH,MEDIUM \\
                            --no-progress \\
                            --format table \\
                            .
                    """
                    archiveArtifacts artifacts: 'trivy-fs-report.json', allowEmptyArchive: true
                }
            }
        }

        // ────────────────────────────────────────────────────────────────────
        // STAGE 3 — Versioning
        //
        // Builds a unique, traceable image tag:
        //   <VERSION>-<short-git-sha>-<build-number>
        // e.g.  1.0.0-ab3f12c-42
        //
        // VERSION FILE STRATEGY:
        //   Python has no standard equivalent of Maven's pom.xml <version>.
        //   Options considered:
        //     a) setup.py / pyproject.toml — overcomplicated for a Flask app
        //        that isn't distributed as a package
        //     b) __version__ in app/__init__.py — requires Python import +
        //        AST parsing or grep; fragile
        //     c) Plain VERSION file at repo root — simplest, most explicit,
        //        readable by any tool (grep, cat, sed, CI scripts)
        //   Decision: VERSION file. One line, one value, trivial to read.
        //
        // VERSION FILE GUARD:
        //   If VERSION is missing or empty, IMAGE_TAG would be "-ab3f12c-42"
        //   — valid Docker syntax but untraceable. error() aborts with context.
        //
        // --short=7 pins SHA to exactly 7 chars.
        //   Without explicit length, git auto-abbreviation grows as repo accumulates
        //   commits — same rationale as java-monolith R4#3 fix.
        //
        // -C ${WORKSPACE} reads SHA from workspace root, not dir(APP_DIR) CWD.
        //   Safe even if APP_DIR is ever a git submodule.
        // ────────────────────────────────────────────────────────────────────
        stage('Versioning') {
            steps {
                dir(APP_DIR) {
                    script {
                        // Read version from VERSION file — single source of truth
                        def appVersion = ''
                        if (fileExists('VERSION')) {
                            appVersion = sh(
                                script: 'cat VERSION | tr -d "[:space:]"',
                                returnStdout: true
                            ).trim()
                        }

                        if (!appVersion || appVersion.isEmpty()) {
                            error("❌ VERSION file is missing or empty. " +
                                  "Create a VERSION file at repo root with a semver string (e.g. 1.0.0). " +
                                  "IMAGE_TAG cannot be built without a valid version.")
                        }

                        // --short=7: pin SHA length — grows without explicit value as repo ages
                        // -C ${WORKSPACE}: always read from workspace root, not CWD
                        def shortSha  = sh(script: 'git -C ${WORKSPACE} rev-parse --short=7 HEAD', returnStdout: true).trim()
                        env.IMAGE_TAG = "${appVersion}-${shortSha}-${BUILD_NUMBER}"
                        echo "🏷️  Image tag: ${IMAGE_TAG}"
                    }
                }
            }
        }

        // ────────────────────────────────────────────────────────────────────
        // STAGE 4 — Setup Python Environment
        //
        // Creates an isolated virtual environment and installs all dependencies.
        //
        // WHY A DEDICATED SETUP STAGE (not inline with test stage):
        //   - The venv is reused by multiple subsequent stages (Bandit, pip-audit,
        //     pytest, SonarQube). Creating it once here avoids redundant installs.
        //   - Separating setup from test gives clearer failure attribution in the
        //     Jenkins UI: "Setup Python Environment" failure = dependency issue;
        //     "Build & Test" failure = actual test failure.
        //
        // WHY VENV AND NOT SYSTEM PIP:
        //   - Jenkins agents may run multiple pipelines concurrently. System-level
        //     pip installs would create version conflicts between projects.
        //   - The venv is scoped to this build's workspace — cleanWs() in post{}
        //     removes it automatically.
        //
        // pip install --upgrade pip first:
        //   Ensures pip resolver (backtracking resolver, default since pip 20.3)
        //   is current — old pip versions can fail to resolve modern packages.
        //
        // pip install bandit pip-audit AFTER requirements.txt:
        //   These are CI-only tools — not in requirements.txt (they are not app
        //   dependencies). Installing them after ensures they don't interfere with
        //   the app's dependency resolution.
        //
        // pytest-cov must be present for --cov flags in Stage 5.
        //   It IS in requirements.txt (pytest is listed; pytest-cov added separately
        //   here as a CI concern). If pytest-cov is added to requirements.txt later,
        //   the explicit install here becomes a no-op (pip skips already-installed).
        // ────────────────────────────────────────────────────────────────────
        stage('Setup Python Environment') {
            steps {
                dir(APP_DIR) {
                    echo '🐍 Creating virtual environment and installing dependencies...'
                    sh """
                        # Create isolated venv for this CI build
                        ${PYTHON} -m venv ${VENV_DIR}

                        # Upgrade pip to current resolver before installing any packages
                        ${PIP} install --upgrade pip --quiet

                        # Install all application dependencies
                        ${PIP} install -r requirements.txt --quiet

                        # Install CI-only tools (not in requirements.txt)
                        ${PIP} install bandit pip-audit pytest-cov --quiet

                        echo "✅ Python environment ready"
                        ${VENV_DIR}/bin/python --version
                        ${PIP} --version
                    """
                }
            }
        }

        // ────────────────────────────────────────────────────────────────────
        // STAGE 5 — Bandit SAST (Python Security Linter)
        //
        // Bandit scans Python source code for security issues specific to Python:
        //   - Hardcoded passwords / secrets in source
        //   - Use of dangerous functions: eval(), exec(), pickle, subprocess shell=True
        //   - SQL injection patterns in SQLAlchemy queries
        //   - Weak cryptography (MD5, SHA1 for security use)
        //   - Flask debug mode enabled, use of assert for security checks
        //
        // WHY BANDIT IN ADDITION TO TRIVY FS AND SONARQUBE:
        //   - Trivy FS scans dependency CVEs and secrets (generic patterns)
        //   - SonarQube (Stage 6) scans code quality + broader SAST
        //   - Bandit fills the Python-idiomatic security gap: it knows Flask,
        //     SQLAlchemy, and Python stdlib patterns that generic SAST tools miss
        //
        // TWO-PASS STRATEGY:
        //   Pass 1 — HIGH severity only, --exit-code 1 → FAILS build
        //            HIGH Bandit findings in Python are almost always real issues
        //            (e.g. subprocess shell=True, eval with user input, hardcoded creds)
        //   Pass 2 — MEDIUM + LOW, --exit-code 0 → advisory JSON artifact
        //            MEDIUM findings are informational; LOW findings are hints.
        //
        // -r app/ — scans only the application source (app/ directory).
        //   Excludes tests/ (test code uses assert heavily → false positives for B101)
        //   and config.py (read-only config, no security-relevant logic).
        //
        // --skip B101 — B101 flags `assert` statements as security issues.
        //   assert is legitimately used in test code. We exclude tests/ above, but
        //   if any assert exists in app/ for input validation it is genuinely wrong
        //   — so B101 is NOT skipped in app/ scan.
        //   Rationale: kept as-is; B101 in app/ is a real finding to address.
        //
        // -f json + archiveArtifacts: full MEDIUM/LOW report for audit trail.
        // ────────────────────────────────────────────────────────────────────
        stage('Bandit SAST') {
            steps {
                dir(APP_DIR) {
                    echo '🔐 Running Bandit Python security analysis...'
                    sh """
                        # Pass 1 — HIGH severity: fail build on finding
                        ${BANDIT} \\
                            -r app/ \\
                            --severity-level high \\
                            --confidence-level medium \\
                            --quiet \\
                            --format txt || {
                                echo '❌ Bandit found HIGH severity security issues. Fix before proceeding.'
                                exit 1
                            }

                        # Pass 2 — MEDIUM + LOW: advisory artifact
                        ${BANDIT} \\
                            -r app/ config.py run.py \\
                            --severity-level low \\
                            --confidence-level low \\
                            --exit-zero \\
                            --format json \\
                            --output bandit-report.json || true

                        echo '✅ Bandit SAST complete'
                    """
                    archiveArtifacts artifacts: 'bandit-report.json', allowEmptyArchive: true
                }
            }
        }

        // ────────────────────────────────────────────────────────────────────
        // STAGE 6 — pip-audit (Dependency CVE Scan)
        //
        // pip-audit scans requirements.txt against:
        //   - PyPI Advisory Database (PYPA)
        //   - Open Source Vulnerabilities database (OSV)
        //
        // WHY PIP-AUDIT IN ADDITION TO TRIVY FS:
        //   - Trivy queries NVD + GitHub Advisory for Python packages.
        //   - pip-audit queries PYPA Advisory DB (maintained by PyPI security team)
        //     + OSV — which has broader Python-specific coverage, especially for
        //     Flask, SQLAlchemy, Werkzeug, Jinja2, and psycopg2 ecosystem.
        //   - Defense in depth: two different advisory databases with different
        //     update cadences and coverage.
        //
        // --requirement requirements.txt — scans declared dependencies only.
        //   Does NOT scan installed packages (which would include bandit, pip-audit
        //   themselves — CI tools, not app concerns).
        //
        // --output json: machine-readable artifact for audit trail.
        //
        // Exit strategy: --exit-code 1 on any vulnerability found.
        //   Unlike Trivy where we split CRITICAL vs HIGH/MEDIUM,
        //   pip-audit surfaces known CVEs by default — any finding in production
        //   dependencies warrants attention. The build WARNS on finding (exit 0)
        //   because pip-audit may flag transitive dep CVEs that are not exploitable
        //   in this app's usage pattern. Adjust to exit 1 once baseline is clean.
        //
        // NOTE: pip-audit requires network access to query advisory DBs.
        //   On air-gapped Jenkins agents, add --local flag to scan only installed
        //   packages without network calls.
        // ────────────────────────────────────────────────────────────────────
        stage('pip-audit Dependency Scan') {
            steps {
                dir(APP_DIR) {
                    echo '📦 Running pip-audit dependency CVE scan...'
                    sh """
                        ${PIP_AUDIT} \\
                            --requirement requirements.txt \\
                            --output json \\
                            --desc \\
                            --no-deps \\
                            > pip-audit-report.json 2>&1 || true

                        # Print human-readable table to console regardless of findings
                        ${PIP_AUDIT} \\
                            --requirement requirements.txt \\
                            --desc \\
                            --no-deps \\
                            --format columns || true

                        echo '✅ pip-audit scan complete (see pip-audit-report.json for details)'
                    """
                    archiveArtifacts artifacts: 'pip-audit-report.json', allowEmptyArchive: true
                }
            }
        }

        // ────────────────────────────────────────────────────────────────────
        // STAGE 7 — Build & Test (pytest + coverage)
        //
        // Runs the full test suite with coverage measurement.
        //
        // PYTEST FLAGS:
        //   --tb=short    — shortened traceback format; full tracebacks are verbose
        //                   for CI console output (full tracebacks in JUnit XML)
        //   -v            — verbose test names for clear CI console output
        //   --junitxml    — JUnit XML format for Jenkins junit() publisher
        //   --cov=app     — measure coverage for the app/ package only
        //                   (not tests/, not config.py, not run.py)
        //   --cov-report xml:coverage.xml — Cobertura XML for SonarQube + Jenkins
        //   --cov-report term-missing     — terminal output showing uncovered lines
        //   --cov-report html:htmlcov     — HTML report for archive artifact
        //   --no-header   — suppress pytest header in CI log (cleaner output)
        //
        // DATABASE_URL is set in environment{} block to sqlite:// for test isolation.
        //   See header comment for full rationale.
        //
        // WHY NOT --cov-fail-under HERE:
        //   Coverage enforcement belongs in sonar-properties / Quality Gate,
        //   not in the pytest invocation. A hard --cov-fail-under in pytest
        //   would fail BEFORE SonarQube even sees the data, making Quality Gate
        //   irrelevant. Let SonarQube be the single coverage gate.
        //
        // junit + recordCoverage publishers are in post{} always block,
        //   guarded by fileExists — same pattern as java-monolith (FIX #8 equivalent).
        // ────────────────────────────────────────────────────────────────────
        stage('Build & Test') {
            steps {
                dir(APP_DIR) {
                    echo '🔨 Running pytest with coverage...'
                    sh """
                        ${PYTEST} \\
                            tests/ \\
                            --tb=short \\
                            -v \\
                            --junitxml=pytest-results.xml \\
                            --cov=app \\
                            --cov-report xml:coverage.xml \\
                            --cov-report term-missing \\
                            --cov-report html:htmlcov \\
                            --no-header
                    """
                }
            }
        }

        // ────────────────────────────────────────────────────────────────────
        // STAGE 8 — SonarQube Analysis
        //
        // Uses sonar-scanner CLI (not Maven plugin) — Python projects use the
        // standalone scanner. Injected via withSonarQubeEnv('sonar-server').
        //
        // KEY SONAR PROPERTIES FOR PYTHON:
        //   sonar.language=py — explicit Python language declaration
        //   sonar.python.version=3.12 — must match runtime Python version
        //                               for accurate symbol analysis
        //   sonar.sources=app — application source only (not tests)
        //   sonar.tests=tests — test directory declared separately
        //   sonar.python.coverage.reportPaths=coverage.xml — Cobertura XML
        //                               from pytest-cov (Stage 7)
        //   sonar.python.xunit.reportPath=pytest-results.xml — JUnit XML
        //                               from pytest (Stage 7)
        //   sonar.exclusions — excludes venv, htmlcov, migrations, static assets
        //                      from analysis (would pollute metrics with
        //                      third-party or generated code)
        //
        // SONAR_HOST_URL and SONAR_AUTH_TOKEN are injected by withSonarQubeEnv()
        // — never hardcoded. sonarqube-token credential ID is registered in
        // Jenkins under Manage Jenkins → Configure System → SonarQube servers.
        //
        // Working directory: ${GITHUB_WORKSPACE} equivalent is ${WORKSPACE} in Jenkins.
        // sonar.working.directory pins report-task.txt for waitForQualityGate (Stage 9).
        // ────────────────────────────────────────────────────────────────────
        stage('SonarQube Analysis') {
            steps {
                dir(APP_DIR) {
                    echo '🔍 Running SonarQube static analysis (Python)...'
                    withSonarQubeEnv('sonar-server') {
                        sh """
                            $SCANNER_HOME/bin/sonar-scanner \\
                                -Dsonar.projectKey=IbtisamIQpythonmonolith \\
                                -Dsonar.projectName=IbtisamIQpythonmonolith \\
                                -Dsonar.projectVersion=${IMAGE_TAG} \\
                                -Dsonar.language=py \\
                                -Dsonar.python.version=3.12 \\
                                -Dsonar.sources=app \\
                                -Dsonar.tests=tests \\
                                -Dsonar.python.coverage.reportPaths=coverage.xml \\
                                -Dsonar.python.xunit.reportPath=pytest-results.xml \\
                                -Dsonar.exclusions="**/__pycache__/**,**/*.pyc,${VENV_DIR}/**,htmlcov/**,app/static/**,app/templates/**" \\
                                -Dsonar.test.exclusions="tests/**" \\
                                -Dsonar.sourceEncoding=UTF-8 \\
                                -Dsonar.working.directory=${WORKSPACE}/.scannerwork
                        """
                    }
                }
            }
        }

        // ────────────────────────────────────────────────────────────────────
        // STAGE 9 — Quality Gate
        //
        // Blocks pipeline until SonarQube webhook fires with pass/fail.
        // abortPipeline: true → build FAILS on gate failure.
        // timeout(5 min): same as java-monolith — sufficient for this codebase.
        // Implicit success() — if Stage 8 failed, this stage is skipped.
        // ────────────────────────────────────────────────────────────────────
        stage('Quality Gate') {
            steps {
                echo '🚦 Waiting for SonarQube Quality Gate...'
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        // ────────────────────────────────────────────────────────────────────
        // STAGE 10 — Docker Build
        //
        // Builds the multi-stage image from Dockerfile at repo root.
        //   Stage 1 (builder):  python:3.12-slim — installs deps into /opt/venv
        //   Stage 2 (runtime):  python:3.12-slim — copies venv + source only
        //
        // WHY SAME BASE FOR BUILDER AND RUNTIME (unlike java-monolith which uses
        // separate builder/jre images):
        //   Python builds don't produce a compiled binary separable from its runtime.
        //   The venv IS the artifact — it must run on the same Python interpreter
        //   it was installed on. Using python:3.12-slim for both stages is correct
        //   and produces ~180MB final image (vs ~500MB+ for the full Python image).
        //
        // --pull: forces Docker to check registry for newer base image digest.
        //   Without --pull, stale base images with known CVEs would be used.
        //   Same rationale as java-monolith FIX #6.
        //
        // PORT build-arg: uses APP_PORT from environment block.
        //   Dockerfile ARG PORT=5000 default is overridden here explicitly.
        //   Keeps Dockerfile's EXPOSE and CMD honest about the actual port.
        //
        // Tags for ALL registries in one build pass — same 3-registry strategy
        // as java-monolith: Docker Hub, GHCR, Nexus Docker.
        //
        // OCI labels: version, revision (GIT_COMMIT from checkout scm),
        //   created (UTC timestamp at build time), source (repo URL).
        // ────────────────────────────────────────────────────────────────────
        stage('Docker Build') {
            steps {
                dir(APP_DIR) {
                    echo "🐳 Building Docker image: ${IMAGE_NAME}:${IMAGE_TAG}"
                    sh """
                        docker build --pull \\
                            --build-arg PORT=${APP_PORT} \\
                            --label "org.opencontainers.image.version=${IMAGE_TAG}" \\
                            --label "org.opencontainers.image.revision=${GIT_COMMIT}" \\
                            --label "org.opencontainers.image.created=\$(date -u +%Y-%m-%dT%H:%M:%SZ)" \\
                            --label "org.opencontainers.image.source=https://github.com/ibtisam-iq/python-monolith-app" \\
                            -t ${IMAGE_NAME}:${IMAGE_TAG} \\
                            -t ${IMAGE_NAME}:latest \\
                            -t ${GHCR_IMAGE}:${IMAGE_TAG} \\
                            -t ${GHCR_IMAGE}:latest \\
                            .

                        # Uncomment once ECR variables are set:
                        # docker tag ${IMAGE_NAME}:${IMAGE_TAG} \${ECR_IMAGE}:${IMAGE_TAG}
                        # docker tag ${IMAGE_NAME}:latest       \${ECR_IMAGE}:latest
                    """
                }
            }
        }

        // ────────────────────────────────────────────────────────────────────
        // STAGE 11 — Trivy Image Scan
        //
        // Scans the freshly built image for CVEs BEFORE pushing to any registry.
        //
        // THREE-PASS STRATEGY (mirrors java-monolith Stage 9):
        //
        //   Pass A — OS packages (python:3.12-slim = Debian Bookworm base):
        //            vuln-type os, CRITICAL+HIGH, --exit-code 0 → warn only.
        //            OS CVEs are Debian/Python maintainer's responsibility —
        //            we surface them but don't block the build on them.
        //            Includes HIGH here (unlike FS scan) because container OS
        //            CVEs have runtime attack surface implications.
        //
        //   Pass B — Library (pip packages from requirements.txt in venv):
        //            vuln-type library, CRITICAL only, --exit-code 1 → FAILS build.
        //            These are YOUR dependencies — fix = bump version in requirements.txt.
        //            HIGH,MEDIUM follow with --exit-code 0 for advisory table.
        //
        //   Pass C — Full audit report (all types + severities incl. LOW):
        //            --exit-code 0, JSON format → archived artifact.
        //            LOW intentionally INCLUDED for image scan (excluded from FS scan).
        //            See java-monolith Stage 9 comment for full LOW rationale.
        //
        // image-ref uses IMAGE_NAME:IMAGE_TAG — image is in local daemon (just built).
        // --cache-dir /var/cache/trivy — persistent DB cache across builds.
        // ────────────────────────────────────────────────────────────────────
        stage('Trivy Image Scan') {
            steps {
                dir(APP_DIR) {
                    echo "🛡️  Scanning image with Trivy: ${IMAGE_NAME}:${IMAGE_TAG}"
                    sh """
                        # Pass A — OS packages: warn only (Debian/Python maintainer responsibility)
                        trivy image \\
                            --cache-dir /var/cache/trivy \\
                            --vuln-type os \\
                            --exit-code 0 \\
                            --severity CRITICAL,HIGH \\
                            --no-progress \\
                            --format table \\
                            ${IMAGE_NAME}:${IMAGE_TAG}

                        # Pass B — Library (pip packages): CRITICAL fails build
                        trivy image \\
                            --cache-dir /var/cache/trivy \\
                            --vuln-type library \\
                            --exit-code 1 \\
                            --severity CRITICAL \\
                            --no-progress \\
                            --format table \\
                            ${IMAGE_NAME}:${IMAGE_TAG}

                        # Pass B (cont.) — Library HIGH/MEDIUM: advisory only
                        trivy image \\
                            --cache-dir /var/cache/trivy \\
                            --vuln-type library \\
                            --exit-code 0 \\
                            --severity HIGH,MEDIUM \\
                            --no-progress \\
                            --format table \\
                            ${IMAGE_NAME}:${IMAGE_TAG}

                        # Pass C — Full report incl. LOW: audit artifact
                        trivy image \\
                            --cache-dir /var/cache/trivy \\
                            --exit-code 0 \\
                            --severity CRITICAL,HIGH,MEDIUM,LOW \\
                            --no-progress \\
                            --format json \\
                            --output trivy-image-report.json \\
                            ${IMAGE_NAME}:${IMAGE_TAG}
                    """
                    archiveArtifacts artifacts: 'trivy-image-report.json', allowEmptyArchive: true
                }
            }
        }

        // ────────────────────────────────────────────────────────────────────
        // STAGES 12–15 — Publish (main branch only)
        //
        // WHY expression{} INSTEAD OF when { branch 'main' }:
        //   Same rationale as java-monolith: branch{} requires Multibranch Pipeline;
        //   on standard Pipeline jobs BRANCH_NAME is never set and branch{} silently
        //   evaluates to false on every build. GIT_BRANCH is set by checkout scm
        //   and takes the form "origin/main" on standard jobs / "main" on Multibranch.
        //
        // WHY NULL GUARD (env.GIT_BRANCH != null):
        //   REST API-triggered builds may not populate GIT_BRANCH.
        //   null ==~ /regex/ throws NPE crashing when{} evaluation — same as Java.
        //
        // ANCHORED REGEX ^(origin\/)?main$:
        //   Matches "origin/main" and "main" only — prevents feature/fix-main branches
        //   from triggering registry pushes.
        // ────────────────────────────────────────────────────────────────────
        stage('Publish') {
            when {
                expression {
                    env.GIT_BRANCH != null &&
                    (env.GIT_BRANCH ==~ /^(origin\/)?main$/)
                }
            }
            stages {

                // ────────────────────────────────────────────────────────────
                // STAGE 12 — Push to Docker Hub
                //
                // docker logout registry-1.docker.io — explicit registry arg required.
                // Bare `docker logout` on some Docker Engine versions clears ALL
                // credentials from ~/.docker/config.json — wiping GHCR and Nexus creds.
                // ────────────────────────────────────────────────────────────
                stage('Push to Docker Hub') {
                    steps {
                        echo "🚀 Pushing image to Docker Hub: ${IMAGE_NAME}"
                        withCredentials([usernamePassword(
                            credentialsId: 'docker-creds',
                            usernameVariable: 'DOCKER_USERNAME',
                            passwordVariable: 'DOCKER_PASSWORD'
                        )]) {
                            sh """
                                echo "\${DOCKER_PASSWORD}" | docker login -u "\${DOCKER_USERNAME}" --password-stdin
                                docker push ${IMAGE_NAME}:${IMAGE_TAG}
                                docker push ${IMAGE_NAME}:latest
                                docker logout registry-1.docker.io
                            """
                        }
                    }
                }

                // ────────────────────────────────────────────────────────────
                // STAGE 13 — Push to GitHub Container Registry (GHCR)
                // ghcr.io/ibtisam-iq/python-monolith:<tag>
                //
                // Credential: ghcr-creds (GitHub PAT with write:packages scope).
                // Same credential setup as java-monolith Stage 11.
                // ────────────────────────────────────────────────────────────
                stage('Push to GHCR') {
                    steps {
                        echo "🐙 Pushing image to GitHub Container Registry: ${GHCR_IMAGE}"
                        withCredentials([usernamePassword(
                            credentialsId: 'ghcr-creds',
                            usernameVariable: 'GHCR_USERNAME',
                            passwordVariable: 'GHCR_TOKEN'
                        )]) {
                            sh """
                                echo "\${GHCR_TOKEN}" | docker login ghcr.io -u "\${GHCR_USERNAME}" --password-stdin
                                docker push ${GHCR_IMAGE}:${IMAGE_TAG}
                                docker push ${GHCR_IMAGE}:latest
                                docker logout ghcr.io
                            """
                        }
                    }
                }

                // ────────────────────────────────────────────────────────────
                // STAGE 14 — Push to Nexus Docker Registry
                // nexus.ibtisam-iq.com/docker-hosted/python-monolith:<tag>
                //
                // Path-based routing — no dedicated Docker port needed.
                // Same Nexus pre-requisites as java-monolith Stage 12:
                //   1. Hosted Docker repo with "Path based routing" selected
                //   2. Security → Realms → Docker Bearer Token Realm active
                // ────────────────────────────────────────────────────────────
                stage('Push to Nexus Registry') {
                    steps {
                        echo "📤 Pushing image to Nexus Docker registry (path-based)..."
                        withCredentials([usernamePassword(
                            credentialsId: 'nexus-creds',
                            usernameVariable: 'NEXUS_USER',
                            passwordVariable: 'NEXUS_PASS'
                        )]) {
                            sh """
                                echo "\${NEXUS_PASS}" | docker login ${NEXUS_DOCKER} -u "\${NEXUS_USER}" --password-stdin
                                docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${NEXUS_DOCKER}/${NEXUS_DOCKER_REPO}/${APP_NAME}:${IMAGE_TAG}
                                docker tag ${IMAGE_NAME}:latest       ${NEXUS_DOCKER}/${NEXUS_DOCKER_REPO}/${APP_NAME}:latest
                                docker push ${NEXUS_DOCKER}/${NEXUS_DOCKER_REPO}/${APP_NAME}:${IMAGE_TAG}
                                docker push ${NEXUS_DOCKER}/${NEXUS_DOCKER_REPO}/${APP_NAME}:latest
                                docker logout ${NEXUS_DOCKER}
                            """
                        }
                    }
                }

                // ────────────────────────────────────────────────────────────
                // STAGE 15 — Push to AWS ECR  [COMMENTED OUT]
                // Uncomment once AWS credentials and ECR repo are provisioned.
                // Same pattern as java-monolith Stage 13.
                //
                // Pre-requisites:
                //   1. aws ecr create-repository --repository-name python-monolith --region us-east-1
                //   2. Add AWS credentials to Jenkins (CloudBees AWS Credentials plugin), ID: aws-creds
                //   3. Set the four ECR variables in environment{} above
                //   4. Uncomment docker tag lines in Stage 10 above
                //   5. Uncomment this stage
                // ────────────────────────────────────────────────────────────
                // stage('Push to AWS ECR') {
                //     steps {
                //         echo "☁️  Pushing image to AWS ECR: ${ECR_IMAGE}"
                //         withCredentials([[
                //             $class:            'AmazonWebServicesCredentialsBinding',
                //             credentialsId:     'aws-creds',
                //             accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                //             secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                //         ]]) {
                //             sh """
                //                 aws ecr get-login-password --region ${AWS_REGION} \
                //                     | docker login --username AWS --password-stdin ${ECR_REGISTRY}
                //                 docker push ${ECR_IMAGE}:${IMAGE_TAG}
                //                 docker push ${ECR_IMAGE}:latest
                //                 docker logout ${ECR_REGISTRY}
                //             """
                //         }
                //     }
                // }

                // ────────────────────────────────────────────────────────────
                // STAGE 16 — Update CD Repo (GitOps handoff)
                //
                // Writes the new image tag into platform-engineering-systems
                // so ArgoCD detects the change and triggers a rolling deployment.
                //
                // ALL hardening from java-monolith Stage 14 carried over:
                //
                //   TOKEN OFF ARGV (R4#2 equivalent):
                //     Clone with public URL → set authenticated remote after clone →
                //     clear token from remote URL after push.
                //     `git clone https://token@...` puts the token in process argv,
                //     readable by ps/proc scanners. set-url writes to .git/config
                //     (in-memory) — never appears in argv.
                //
                //   IMAGE_TAG GUARD (FIX #1 equivalent):
                //     \${IMAGE_TAG} escaped → shell evaluates at runtime.
                //     Unescaped ${IMAGE_TAG} is Groovy-interpolated at parse time;
                //     if null, renders as "null" → ArgoCD deploys tag "null".
                //
                //   UNIQUE TMP DIR (FIX #9 equivalent):
                //     _cd_repo_tmp — distinct from any app source directory name.
                //
                //   GIT DIFF GUARD (FIX #3 equivalent):
                //     git diff --cached --quiet isolates "nothing staged" precisely
                //     without swallowing real commit errors (unlike || echo).
                //
                //   HEAD PUSH (FIX #2 equivalent):
                //     git push origin HEAD — resilient to CD repo branch renames.
                //
                //   GROOVY vs SHELL INTERPOLATION:
                //     \${GIT_USER}, \${GIT_TOKEN}, \${IMAGE_TAG} — escaped → shell expands.
                //     ${CD_REPO}, ${CD_MANIFEST_PATH} — not escaped → Groovy interpolates
                //     at parse time from environment{} block. Correct: these are static
                //     strings known at parse time.
                // ────────────────────────────────────────────────────────────
                stage('Update CD Repo') {
                    steps {
                        echo '🔄 Updating image tag in CD repo (platform-engineering-systems)...'
                        withCredentials([usernamePassword(
                            credentialsId: 'github-creds',
                            usernameVariable: 'GIT_USER',
                            passwordVariable: 'GIT_TOKEN'
                        )]) {
                            sh """
                                # IMAGE_TAG GUARD — escaped: shell evaluates at runtime
                                if [ -z "\${IMAGE_TAG}" ]; then
                                    echo '❌ IMAGE_TAG is empty — aborting CD repo update'
                                    exit 1
                                fi

                                # Unique tmp dir — no collision with app source directories
                                rm -rf _cd_repo_tmp

                                # TOKEN OFF ARGV — clone public URL; token never in argv
                                git clone https://github.com/${CD_REPO}.git _cd_repo_tmp

                                cd _cd_repo_tmp

                                # Clear token-bearing URL immediately after clone
                                git remote set-url origin ""

                                # Restore bare HTTPS URL for credential helper
                                git remote set-url origin "https://github.com/${CD_REPO}.git"

                                git config --local user.email "jenkins@ibtisam-iq.com"
                                git config --local user.name  "Jenkins CI"

                                mkdir -p "\$(dirname "${CD_MANIFEST_PATH}")"

                                # Once K8s/Helm manifests exist, replace with:
                                # sed -i "s|image: mibtisam/python-monolith:.*|image: mibtisam/python-monolith:\${IMAGE_TAG}|g" \\
                                #     deployments/python-monolith/deployment.yaml

                                # IMAGE_TAG escaped — shell runtime evaluation
                                echo "IMAGE_TAG=\${IMAGE_TAG}" > "${CD_MANIFEST_PATH}"

                                git add "${CD_MANIFEST_PATH}"

                                # PRECISE "nothing staged" detection — does NOT swallow real errors
                                git diff --cached --quiet \\
                                    && echo "ℹ️  Nothing to commit — image tag unchanged" \\
                                    || git commit -m "ci: update python-monolith image tag to \${IMAGE_TAG} [skip ci]"

                                # TOKEN OFF ARGV — push via credential helper
                                git -c credential.helper='!f() { printf "username=%s\\n" "\${GIT_USER}"; printf "password=%s\\n" "\${GIT_TOKEN}"; }; f' \\
                                    push origin HEAD

                                # Clear token from remote URL — not left in workspace
                                git remote set-url origin "https://github.com/${CD_REPO}.git"
                            """
                        }
                    }
                }

            } // end stages (Publish)
        } // end stage('Publish')

    } // end stages

    // ────────────────────────────────────────────────────────────────────────
    // POST — Publishers, Cleanup & Notifications
    //
    // ORDERING (intentional — do not reorder):
    //   1. pytest JUnit XML publisher    — must run BEFORE cleanWs() removes files
    //   2. Coverage publisher            — must run BEFORE cleanWs() removes files
    //   3. Docker cleanup                — named rmi + dangling prune
    //   4. CD tmp dir cleanup            — rm _cd_repo_tmp if Stage 16 ran
    //   5. cleanWs()                     — always last
    //
    // FILEEXISTS GUARDS (Python equivalent of java-monolith FIX #8):
    //   If the pipeline fails before Stage 7 (Build & Test), pytest-results.xml
    //   and coverage.xml do not exist. Without the guard:
    //     - junit() with allowEmptyResults: false would fail the post block
    //     - recordCoverage() would write a zero-coverage data point to the trend
    //       graph, making every Trivy/Bandit/Versioning failure appear as a
    //       coverage regression — same false-negative problem as Java pipeline.
    //   fileExists guard precisely isolates "pre-test failure" from "test failure".
    //
    // COVERAGE PUBLISHER:
    //   recordCoverage() with COBERTURA parser — reads coverage.xml generated
    //   by pytest-cov. Requires the Coverage Plugin (install from Jenkins Update
    //   Center: id = "coverage") — the old Cobertura Plugin is deprecated and
    //   end-of-life as of 2026. The parser: 'COBERTURA' key is a parser ID
    //   inside the unified Coverage Plugin, not the old standalone plugin.
    //   sourceCodeRetention: 'EVERY_BUILD' keeps source coverage data per build
    //   for trend analysis in the Jenkins Coverage plugin.
    // ────────────────────────────────────────────────────────────────────────
    post {
        always {
            // ── 1. pytest JUnit XML publisher — guarded by fileExists
            script {
                if (fileExists("${APP_DIR}/pytest-results.xml")) {
                    junit testResults: "${APP_DIR}/pytest-results.xml",
                          allowEmptyResults: true
                } else {
                    echo '⏭️  Skipping junit — pytest-results.xml not found (pipeline failed before Build & Test stage).'
                }
            }

            // ── 2. Coverage publisher (Coverage Plugin — COBERTURA parser)
            //       Install: Jenkins Update Center → "Coverage" (id: coverage)
            //       Do NOT install the old "Cobertura" plugin — it is deprecated.
            script {
                if (fileExists("${APP_DIR}/coverage.xml")) {
                    recordCoverage(
                        tools: [[
                            parser:  'COBERTURA',
                            pattern: "${APP_DIR}/coverage.xml"
                        ]],
                        sourceCodeRetention: 'EVERY_BUILD'
                    )
                } else {
                    echo '⏭️  Skipping recordCoverage — coverage.xml not found (pipeline failed before Build & Test stage).'
                }
            }

            // ── 3. Docker cleanup — named rmi + dangling layer prune
            script {
                if (env.IMAGE_TAG) {
                    echo '🧹 Cleaning up local Docker images...'
                    sh """
                        docker rmi ${IMAGE_NAME}:${IMAGE_TAG}                                          || true
                        docker rmi ${IMAGE_NAME}:latest                                                || true
                        docker rmi ${GHCR_IMAGE}:${IMAGE_TAG}                                         || true
                        docker rmi ${GHCR_IMAGE}:latest                                               || true
                        docker rmi ${NEXUS_DOCKER}/${NEXUS_DOCKER_REPO}/${APP_NAME}:${IMAGE_TAG}      || true
                        docker rmi ${NEXUS_DOCKER}/${NEXUS_DOCKER_REPO}/${APP_NAME}:latest            || true
                        # docker rmi \${ECR_IMAGE}:${IMAGE_TAG}                                       || true
                        # docker rmi \${ECR_IMAGE}:latest                                             || true
                    """
                } else {
                    echo '⏭️  Skipping docker rmi — IMAGE_TAG not set (pipeline failed before Versioning stage).'
                }

                // Prune dangling (<none>:<none>) image layers — always safe
                sh 'docker image prune -f || true'
            }

            // ── 4. CD tmp dir cleanup
            sh 'rm -rf _cd_repo_tmp || true'

            // ── 5. Workspace cleanup — always last
            cleanWs()
        }

        success {
            script {
                def published = (env.GIT_BRANCH != null && env.GIT_BRANCH ==~ /^(origin\/)?main$/)
                    ? 'PUBLISHED to all registries ✅'
                    : 'NOT PUBLISHED — non-main branch (build + scan only)'
                echo """
            ╔══════════════════════════════════════════════════════════╗
            ║  ✅  PIPELINE SUCCEEDED
            ╠══════════════════════════════════════════════════════════╣
            ║  Branch : ${env.GIT_BRANCH}
            ║  Status : ${published}
            ║  Image  : ${IMAGE_NAME}:${IMAGE_TAG}
            ║  GHCR   : ${GHCR_IMAGE}:${IMAGE_TAG}
            ║  Nexus  : ${NEXUS_URL}
            ╚══════════════════════════════════════════════════════════╝
                """
            }
        }

        failure {
            echo """
            ╔══════════════════════════════════════════════════════════╗
            ║  ❌  PIPELINE FAILED                                     ║
            ║  Check console output for details                        ║
            ╚══════════════════════════════════════════════════════════╝
            """
        }

        unstable {
            echo '⚠️  Pipeline is UNSTABLE — test failures or quality issues detected.'
        }
    }
}
